spring:
  application:
    name: web-api
  mail:
    host: localhost # smtp.gmail.com
    port: 1025 # 587
    username: MAIL_APP_USERNAME
    password: MAIL_APP_PASSWORD
    properties:
      mail:
      smtp:
        auth: false
        timeout: 5000
        starttls:
          enable: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ticketing
    username: root
    password: pw@1234
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: false
    hibernate:
      ddl-auto: update
  devtools:
    livereload:
      enabled: true

decorator:
  datasource:
    p6spy:
      enable-logging: true

load-dummy-data:
  enabled: false

logging:
  level:
    root: INFO
    com.cd18.application: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true